idf_component_register(
    SRCS
        "app_main.c"
        "host_config.c"
        "photoframe_plugin.c"
        "module_slots.c"
        "module_format.c"
        "app_manifest.c"
        "app_services.c"
        "app_manager.c"
        "app_button.c"
        "app_boot.c"
        "host_abi.c"
        "push_server.c"
        "wifi_station.c"
        "wifi_profiles.c"
        "wifi_profiles_json.c"
        "wifi_sd.c"
    INCLUDE_DIRS "."
    PRIV_REQUIRES
        photopainter_board
        esp_event
        esp_http_server
        esp_netif
        esp_timer
        esp_wifi
        fatfs
        sdmmc
        esp_driver_sdmmc
        esp_driver_gpio
        esp_driver_i2c
        esp_driver_spi
        freertos
        heap
        nvs_flash
        esp_partition
        mbedtls
)
