idf_component_register(
    SRCS
        "app_main.c"
        "host_config.c"
        "photoframe_plugin.c"
        "module_slots.c"
        "module_format.c"
        "host_abi.c"
        "push_server.c"
        "wifi_station.c"
    INCLUDE_DIRS "."
    PRIV_REQUIRES
        esp_event
        esp_http_server
        esp_netif
        esp_timer
        esp_wifi
        esp_driver_gpio
        esp_driver_i2c
        esp_driver_spi
        freertos
        heap
        nvs_flash
        esp_partition
        mbedtls
)
